
spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    password: suhyuk1027
    username: suhyuk0544


  thymeleaf:

    suffix: .html

    prefix: classpath:templates/

    cache: false

server:

  port: 8080

  tomcat:
    connection-timeout: 20000
  servlet:
    session:
      timeout: 60m